# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/malayalam-text-classifier',
                'doc_host': 'https://smc.github.io',
                'git_url': 'https://github.com/smc/malayalam-text-classifier',
                'lib_path': 'malayalam_text_classifier'},
  'syms': { 'malayalam_text_classifier.core': { 'malayalam_text_classifier.core.foo': ( 'core.html#foo',
                                                                                        'malayalam_text_classifier/core.py')}}}